function cellInfo = TractionSystem_In_Vehicle_Dynamics(varargin) 
% TRACTIONSYSTEM_IN_VEHICLE_DYNAMICS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_TractionSystem_In_Vehicle_Dynamics', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'Velocity', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), sprintf('Tangential velocity at the wheel rail contact point')}; ...
{'Bogie', 2, 'Bus: BD_TractionSystem_In_Vehicle_Dynamics_Bogie', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
