function cellInfo = ElectricalSystem_In_Vehicle_SignalSys(varargin) 
% ELECTRICALSYSTEM_IN_VEHICLE_SIGNALSYS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_ElectricalSystem_In_Vehicle_SignalSys', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'NotImmobilise', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LeftSideDoorEnable', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RightSideDoorEnable', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ATCZeroSpeed', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'NotSafetyBrake', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LeftSideDoorOpen', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RightSideDoorOpen', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ATOTraction', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ATONotBrake', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LeftDoorOpenIndicator', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RightDoorOpenIndicator', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UndergroundSection', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ATOStartIndicator', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SBResetIndicator', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LeftDoorReleaseIndicator', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RightDoorReleaseIndicator', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ATOState', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ROSIndication', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'NoEmergencyBrakeOrder', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LeftHoldDoorClose', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RightHoldDoorClose', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EmerDetrainDoorLockRelay', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'WakeUpCommand', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UTOPBIndicator', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UTOModeActive', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ATCCabActivation', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ATOTBDemand', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TractionForward', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DerailmentDetected', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ObstacleHardCollision', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ObstacleSoftCollision', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
