function cellInfo = CBTC_Out_Vehicle(varargin) 
% CBTC_OUT_VEHICLE returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_CBTC_Out_Vehicle', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'OnBoard', 1, 'Bus: BD_CBTC_Out_Vehicle_Onboard', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Platform', 1, 'Bus: BD_CBTC_Out_Vehicle_Platform', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Electrical', 1, 'Bus: BD_CBTC_Out_Vehicle_Electrical', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMS', 1, 'Bus: BD_CBTC_Out_Vehicle_TCMS', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DMI', 1, 'Bus: BD_CBTC_Out_Vehicle_DMI', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
