function [bus_names, bus_prefix, bus_dir] = prj_bus_names()

bus_names = { ...
    'PneumaticsSystem_Cfg_Vehicle',...
    'PneumaticsSystem_Cfg_Vehicle_Equipment',...
    'PneumaticsSystem_In_Overrides',...
    'PneumaticsSystem_In_Vehicle',...
    'PneumaticsSystem_In_Vehicle_ElectricalSignals',...
    'PneumaticsSystem_In_Vehicle_ElectricalSignals_Bogie',...
    'PneumaticsSystem_In_Vehicle_Faults',...
    'PneumaticsSystem_In_Vehicle_InputControlStates',...
    'PneumaticsSystem_In_Vehicle_PhysicalSignals',...
    'PneumaticsSystem_Out_Vehicle'...
    'PneumaticsSystem_Out_Vehicle_Audio'...
    'PneumaticsSystem_Out_Vehicle_AxleBrakes'...
    'PneumaticsSystem_Out_Vehicle_Coupling'...
    'PneumaticsSystem_Out_Vehicle_Debug'...
    'PneumaticsSystem_Out_Vehicle_Debug_Bogie'...
    'PneumaticsSystem_Out_Vehicle_Gauges'...
    'PneumaticsSystem_Out_Vehicle_Gauges_Bogie'...
    'PneumaticsSystem_Out_Vehicle_Switches'...
    'PneumaticsSystem_Out_Vehicle_Switches_Bogie'...
    'PneumaticsSystem_Out_Vehicle_Transducers'...
    'PneumaticsSystem_Out_Vehicle_Transducers_Bogie'...
    'PneumaticsSystem_Out_Vehicle_TCMS'...
    'PneumaticsSystem_Out_Vehicle_TCMS_Bogie'...
    'PneumaticsSystem_Prm'...
    'PneumaticsSystem_Prm_AirSuspension'...
    'PneumaticsSystem_Prm_AuxiliaryReservoir'...
    'PneumaticsSystem_Prm_BrakeControl',...
    'PneumaticsSystem_Prm_BrakeCylinder'...
    'PneumaticsSystem_Prm_BrakeReservoir'...
    'PneumaticsSystem_Prm_Horn'...
    'PneumaticsSystem_Prm_MainReservoir'...
    'PneumaticsSystem_Prm_MainReservoirPipe'...
    'PneumaticsSystem_Prm_Pantograph'...
    'PneumaticsSystem_Prm_ParkBrakes'...
    'PneumaticsSystem_Prm_Sanding'...
    'PneumaticsSystem_Prm_VCB'...
};
    
bus_prefix = 'BD_';

%find the bus_dir based on the relative
%path to this file (prj_bus_names.m)
m_dir = fileparts(mfilename('fullpath'));
bus_dir = fullfile(m_dir, '../data/bus');

end