function cellInfo = TractionSystem_Test_Vehicle(varargin) 
% TRACTIONSYSTEM_TEST_VEHICLE returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_TractionSystem_Test_Vehicle', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'NormalMode', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BoostMode', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'WashMode', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RMFMode', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EmergencyTractionMode', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EmergencyVentilationMode', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TractionAdjustmentFactor', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TractionSupportedMass', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TractionInterlock', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BrakingInterlock', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SpeedLimit', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
