function cellInfo = TCMSSystem_Out_Vehicle_Control_TractionBraking(varargin) 
% TCMSSYSTEM_OUT_VEHICLE_CONTROL_TRACTIONBRAKING returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_TCMSSystem_Out_Vehicle_Control_TractionBraking', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'PWRandBRKBothApplied', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TractionCutModeSelectorInATPATOUTO', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECUFaulty', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TractionCommand', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EDBrakingCommand', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HTERequired', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'VehicleDerailed', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSIsolateCI', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CIIsolated', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bogie', 2, 'Bus: BD_TCMSSystem_Out_Vehicle_Control_TractionBraking_Bogie', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SpeedSensorFault', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSSpeedLimit', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSSpeedLimitCause', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU1AxleLockedWheelSet1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU2AxleLockedWheelSet2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
