function cellInfo = CBTC_Out_Vehicle_Electrical(varargin) 
% CBTC_OUT_VEHICLE_ELECTRICAL returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_CBTC_Out_Vehicle_Electrical', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'ATOTraction', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ATONotBrake', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ATOTBDemand', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'NoEmergencyBrakeOrder', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ROSIndication', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ATOStartIndication', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ATCSBResetIndication', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LeftHoldDoorClose', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RightHoldDoorClose', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ATCZeroSpeed', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'WakeUpCommand', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UTOPBIndicator', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UTOModeActive', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ATCCabActivation', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'NotImmobilise', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TractionForward', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EmergencyDetrainmentDoorLocked', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
