function [bus_names, bus_prefix, bus_dir] = prj_bus_names()

bus_names = { ...
    'CouplingSystem_Cfg_Vehicle',...
    'CouplerMimic_InterfaceData',...
    'CouplerSystem_InterfaceData',...
	'CouplingSystem_In_Vehicle',...
    'CouplingSystem_In_Vehicle_SingleCoupler',...
    'CouplingSystem_In_Vehicle_Coupler_Dynamics',...
    'CouplingSystem_In_Vehicle_Coupler_Electrical',...
    'CouplingSystem_In_Vehicle_Coupler_PhysicalSignals',...
    'CouplingSystem_In_Vehicle_Coupler_Pneumatics',...
	'CouplingSystem_Out_Vehicle'...
    'CouplingSystem_Out_Vehicle_Audio',...
    'CouplingSystem_Out_Vehicle_Coupler',...
    'CouplingSystem_Out_Vehicle_SingleCoupler',...
    'CouplingSystem_Out_Vehicle_Debug',...
    'CouplingSystem_Out_Vehicle_Debug_PerCoupler',...
    'CouplingSystem_Out_Vehicle_OutputControlStates',...
    'CouplingSystem_Out_Vehicle_Coupler_PhysicalSignals',...
	'CouplingSystem_Prm'...
    };
bus_prefix = 'BD_';

%find the bus_dir based on the relative
%path to this file (prj_bus_names.m)
m_dir = fileparts(mfilename('fullpath'));
bus_dir = fullfile(m_dir, '../data/bus');
%  'CouplingSystem_In_DCU_Overrides',...
end