function cellInfo = PneumaticsSystem_In_Overrides(varargin) 
% PNEUMATICSSYSTEM_IN_OVERRIDES returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_PneumaticsSystem_In_Overrides', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'Reset', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'StartupState', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Initial state of the train\n0 = Powered Down\n1 = Powered\n2 = Train Running Electric\n3 = Train Running Diesel')}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
