function cellInfo = TCMSSystem_In_Vehicle_InputControlStates(varargin) 
% TCMSSYSTEM_IN_VEHICLE_INPUTCONTROLSTATES returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_TCMSSystem_In_Vehicle_InputControlStates', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'TractionBrakeController', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HeadLightSwitch', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ParkBrakeIsolationCockBogie1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ParkBrakeIsolationCockBogie2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bogie1IsolationCmd', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bogie2IsolationCmd', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EPIC', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ASCOEnd1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ASCOEnd2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ASIsolationCock', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SR', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ModeSelector', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EBPB', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SafetyCutoutSS', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MREPICEnd1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MREPICEnd2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CabSaloonPartitionDoorOpen', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EmergencyDoorCoverRemoved', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorLoopBypassActive', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DeadManBypass', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ControlKey', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LeftDoor1Lockout', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LeftDoor2Lockout', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LeftDoor3Lockout', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LeftDoor4Lockout', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RightDoor1Lockout', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RightDoor2Lockout', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RightDoor3Lockout', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RightDoor4Lockout', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LeftDoor1EED', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LeftDoor2EED', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LeftDoor3EED', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LeftDoor4EED', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RightDoor1EED', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RightDoor2EED', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RightDoor3EED', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RightDoor4EED', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RampCoverLockingLever', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HornManuallyIsolated', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BIC1Inside', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BIC1Outside', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BIC2Inside', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BIC2Outside', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
