function cellInfo = CouplingSystem_Out_Vehicle_Debug_PerCoupler(varargin) 
% COUPLINGSYSTEM_OUT_VEHICLE_DEBUG_PERCOUPLER returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_CouplingSystem_Out_Vehicle_Debug_PerCoupler', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'AutoCouple', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AvailableReady', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'OurCoupled', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Uncoupled', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TheirsCoupled', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BothCoupled', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CouplerTypeMatched', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TheirsExtensionRate', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ModelledTrainCouplerType', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'OtherTrainCouplerType', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
