function [bus_names, bus_prefix, bus_dir] = prj_bus_names()

bus_names = { ...
    'TractionSystem_Cfg_Vehicle',...
    'TractionSystem_In_Faults',...
    'TractionSystem_In_Faults_Bogie',...
    'TractionSystem_In_Overrides',...
    'TractionSystem_In_Vehicle',...
    'TractionSystem_In_Vehicle_ElectricalSystem',...
    'TractionSystem_In_Vehicle_ElectricalSystem_Bogie',...
    'TractionSystem_In_Vehicle_Dynamics',...
    'TractionSystem_In_Vehicle_Dynamics_Bogie',...
    'TractionSystem_In_Vehicle_TCMS',...
    'TractionSystem_In_Vehicle_TCMS_Bogie',...
    'TractionSystem_Int_BogieControl',...
    'TractionSystem_Int_BogieOutputs',...
    'TractionSystem_Int_Vehicle_Dynamics',...
    'TractionSystem_Out_Vehicle',...
    'TractionSystem_Out_Vehicle_Audio',...
    'TractionSystem_Out_Vehicle_BCU',...
    'TractionSystem_Out_Vehicle_BCU_Bogie',...
    'TractionSystem_Out_Vehicle_Dynamics',...
    'TractionSystem_Out_Vehicle_ElectricalSystem',...
	'TractionSystem_Out_Vehicle_ElectricalSystem_Bogie', ... 
    'TractionSystem_Out_Vehicle_TCMS',...
    'TractionSystem_Out_Vehicle_TCMS_Bogie',...
    'TractionSystem_Out_Vehicle_TCMS_Trafo_TCU',...
    'TractionSystem_Out_Vehicle_TCU',...
    'TractionSystem_Prm',...
    'TractionSystem_Prm_Contour',...
    'TractionSystem_Test_Vehicle',...
};
    
bus_prefix = 'BD_';

%find the bus_dir based on the relative
%path to this file (prj_bus_names.m)
m_dir = fileparts(mfilename('fullpath'));
bus_dir = fullfile(m_dir, '../data/bus');

end