function cellInfo = ElectricalSystem_Out_Vehicle_MiscOutputs(varargin) 
% ELECTRICALSYSTEM_OUT_VEHICLE_MISCOUTPUTS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_ElectricalSystem_Out_Vehicle_MiscOutputs', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'PAPIS', 1, 'Bus: BD_ElectricalSystem_Out_Vehicle_MiscOutputs_PAPIS', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('PAPIS DataBus')}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
