function cellInfo = IOControls_Out_Vehicle_OutputStates(varargin) 
% IOCONTROLS_OUT_VEHICLE_OUTPUTSTATES returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_IOControls_Out_Vehicle_OutputStates', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'HornPBLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'CabConsoleLightPBLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'CabConsoleLight', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'LeftDoorClosePBOperatingPanel1Lamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'RightDoorClosePBOperatingPanel1Lamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'LeftDoorOpenPBOperatingPanel1Lamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'RightDoorOpenPBOperatingPanel1Lamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'CabMainLightPBLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'CabMainLight', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'ParkingBrakeOnSwitchLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'ParkingBrakeOffSwitchLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'DoorCloseAnnouncementPBLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'ROSPBLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'UTOPBLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'ATOStartPBLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'EmergencyBrakeResetPBLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'MRAirGaugeMRPressure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BCSRDualPressureGaugeBCPressure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BCSRDualPressureGaugeSRPressure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CallOnLightPBLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'VCBOpenPBLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'LIMPHomePBLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'PowerOffPBLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'PantoDownPBLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'VCBClosePBLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'LeftDoorOpenPBOperatingPanel2Lamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'LeftDoorOpenPB1OperatingPanel2Lamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'LeftDoorClosePBOperatingPanel2Lamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'PantoUpPBLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'APSFaultIndicator', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'PowerFaultIndicator', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'EmergencyBrakeIndicator', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'VCBTripIndicator', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'LineVoltageIndicator', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'OtherCabOccupiedIndicator', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'ParkingBrakeIndicator', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'AllDoorCloseIndicator', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'HVACFaultIndicator', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'SaloonDoorCloseIndicator', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'UncouplePBLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'FlasherLightPBLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'FloodLightPBLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'BatteryResetPBLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'RightDoorOpenPBOperatingPanel5Lamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'RightDoorOpenPB1OperatingPanel5Lamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'RightDoorClosePBOperatingPanel5Lamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'LampTestPBLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'WFLTestPBLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'DoorIndicator', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'Ramp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Folded\nUnfolded')}; ...
{'EmergencyDoor', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Closed\nOpen')}; ...
{'RampSupportDown', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Folded\nUnfolded')}; ...
{'GasSpringLocked', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Closed\nOpen')}; ...
{'LeftDoor1Position', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Closed\nOpen')}; ...
{'LeftDoor2Position', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Closed\nOpen')}; ...
{'LeftDoor3Position', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Closed\nOpen')}; ...
{'LeftDoor4Position', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Closed\nOpen')}; ...
{'RightDoor1Position', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Closed\nOpen')}; ...
{'RightDoor2Position', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Closed\nOpen')}; ...
{'RightDoor3Position', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Closed\nOpen')}; ...
{'RightDoor4Position', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Closed\nOpen')}; ...
{'LeftDoor1aPosition', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Closed\nOpen')}; ...
{'LeftDoor1InsideLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('OFF\nRed On\nAmber Flashing\nYellow On')}; ...
{'LeftDoor2InsideLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('OFF\nRed On\nAmber Flashing\nYellow On')}; ...
{'LeftDoor3InsideLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('OFF\nRed On\nAmber Flashing\nYellow On')}; ...
{'LeftDoor4InsideLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('OFF\nRed On\nAmber Flashing\nYellow On')}; ...
{'RightDoor1InsideLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('OFF\nRed On\nAmber Flashing\nYellow On')}; ...
{'RightDoor2InsideLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('OFF\nRed On\nAmber Flashing\nYellow On')}; ...
{'RightDoor3InsideLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('OFF\nRed On\nAmber Flashing\nYellow On')}; ...
{'RightDoor4InsideLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('OFF\nRed On\nAmber Flashing\nYellow On')}; ...
{'LeftDoor1OutsideLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('OFF\nRed On\nAmber Flashing\nYellow On')}; ...
{'LeftDoor2OutsideLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('OFF\nRed On\nAmber Flashing\nYellow On')}; ...
{'LeftDoor3OutsideLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('OFF\nRed On\nAmber Flashing\nYellow On')}; ...
{'LeftDoor4OutsideLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('OFF\nRed On\nAmber Flashing\nYellow On')}; ...
{'RightDoor1OutsideLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('OFF\nRed On\nAmber Flashing\nYellow On')}; ...
{'RightDoor2OutsideLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('OFF\nRed On\nAmber Flashing\nYellow On')}; ...
{'RightDoor3OutsideLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('OFF\nRed On\nAmber Flashing\nYellow On')}; ...
{'RightDoor4OutsideLamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('OFF\nRed On\nAmber Flashing\nYellow On')}; ...
{'FloodLight', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'FlasherLight', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nFlashing')}; ...
{'UTOOrRMLight', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn\nFlashing')}; ...
{'MarkerOrTailLight', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nWhite\nRed')}; ...
{'HeadLight', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nLow\nHigh')}; ...
{'WaitIndicator', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'CallIndicator', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'TalkIndicator', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'PantographPosition', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Fully Lowered\nFully Raised')}; ...
{'WiperPositionLeft', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'WiperPositionCenter', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'WiperPositionRight', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'WiperWash', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'VehicleDerailed', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
{'VehicleBogieDerailed', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Off\nOn')}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
