function cellInfo = TCMSSystem_In_Vehicle_Faults(varargin) 
% TCMSSYSTEM_IN_VEHICLE_FAULTS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_TCMSSystem_In_Vehicle_Faults', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'MasterControllerandTrainLineIncongruence', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSDisplayHanged', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'NeutralZoneVCBBackupFunctionActivated', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CCUCommunicationError', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UnexpectedDoorOpeningDetectedByCC', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RIO1Fault', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RIO1RIO2Fault', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ERFault', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TractionCutModeSelectorInATPATOUTO', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HighTractiveEffortRequired', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DynamicBrakeCutOut', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECUPWRAndBRKCmdAtSameTime', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU2MinorFault', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECUMajorFault', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECUMajorFaultWired', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
