function cellInfo = MotionBase_In_Vehicle_Dynamics_Transform(varargin) 
% MOTIONBASE_IN_VEHICLE_DYNAMICS_TRANSFORM returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_MotionBase_In_Vehicle_Dynamics_Transform', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'Position', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'OrientationDCM', [3 3], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'OrientationQ', 4, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'H', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'P', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'R', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
