function cellInfo = CouplingSystem_In_Vehicle(varargin) 
% COUPLINGSYSTEM_IN_VEHICLE returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_CouplingSystem_In_Vehicle', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'ReleaseCoupler', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Coupler', 2, 'Bus: BD_CouplingSystem_In_Vehicle_SingleCoupler', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DynamicsCouplers', 2, 'Bus: BD_CouplingSystem_In_Vehicle_Coupler_Dynamics', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
