function cellInfo = SimIntegration_Out_Vehicle_Audio(varargin) 
% SIMINTEGRATION_OUT_VEHICLE_AUDIO returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_SimIntegration_Out_Vehicle_Audio', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'VigilanceAlarm', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HornHigh', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HornLow', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bell', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SaloonDoorOpeningBuzzer', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SaloonDoorClosingBuzzer', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorWarningBuzzer', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EEDEADOperated', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'VCBOpenSound', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'VCBCloseSound', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CompressorStartAndRunSound', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'FlasherLightOperationSound', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DeadmanAlarm', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PantographLowering', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'WheelSlip', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'WheelSlide', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AirBrakeRelease', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PantographRaising', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'WiperSound', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EmergencyBrakeApplicationSound', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BPVentAudio', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CollisionDetectionCoupling', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Derailment', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MechanicalUncouple', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PneumaticPressureRelease', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ObstacleSoftCollision', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
