function cellInfo = ElectricalSystem_Wires_OrientationWires(varargin) 
% ELECTRICALSYSTEM_WIRES_ORIENTATIONWIRES returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_ElectricalSystem_Wires_OrientationWires', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'TWForward', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TWReverse', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_LeftDoorClose', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_RightDoorClose', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_LeftDoorOpen', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_RightDoorOpen', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW81114', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW81115', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_LDE', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_RDE', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_LHDC', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_RHDC', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_LDO_LH', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_RDO_LH', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
