function cellInfo = TCMSSystem_Out_Vehicle_Display_PneumaticsSystem_Bogie(varargin) 
% TCMSSYSTEM_OUT_VEHICLE_DISPLAY_PNEUMATICSSYSTEM_BOGIE returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_TCMSSystem_Out_Vehicle_Display_PneumaticsSystem_Bogie', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'BrakeCylinderPressureGauge', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('Pa'), sprintf('Brake Cylinder Gauge needle pressure in Pa (gauge pressure) \n This is a single location.')}; ...
{'ParkBrakePressureGauge', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('Pa'), sprintf('Park Brake Gauge needle pressure in Pa (gauge pressure) \n This is a single location.')}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
