function cellInfo = PneumaticsSystem_Out_Vehicle_Debug_Bogie(varargin) 
% PNEUMATICSSYSTEM_OUT_VEHICLE_DEBUG_BOGIE returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_PneumaticsSystem_Out_Vehicle_Debug_Bogie', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'BrakeCylinderControlPressure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('Pa'), sprintf('Pressure in Pa (absolute pressure)')}; ...
{'BrakeCylinderPressure', 2, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('Pa'), sprintf('Pressure in Pa (absolute pressure)')}; ...
{'ParkBrakePressure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('Pa'), sprintf('Pressure in Pa (absolute pressure)')}; ...
{'SandingSystemPressure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('Pa'), sprintf('Pressure in Pa (absolute pressure)')}; ...
{'AirSuspensionPressure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('Pa'), sprintf('Pressure in Pa (absolute pressure)')}; ...
{'AirSuspPressureDiff', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('Pa'), sprintf('Pressure in Pa (absolute pressure)')}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
