function cellInfo = PneumaticsSystem_Prm_ParkBrakes(varargin) 
% PNEUMATICSSYSTEM_PRM_PARKBRAKES returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_PneumaticsSystem_Prm_ParkBrakes', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'ParkBrakesPerBogieAxle', 2, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('1 - Bogie Axle is equipped with park brakes\n0 - Bogie Axle is not equipped with park brakes')}; ...
{'ParkBrakePressures', 2, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Minimum and Maximum Park Brake Pressures resulting in park braking force')}; ...
{'ParkBrakeForces', 2, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Park Braking Forces corresponding to minimum and maximum park brake pressures')}; ...
{'SwitchONPressure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('Pa'), ''}; ...
{'SwitchOFFPressure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('Pa'), ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
