function cellInfo = PneumaticsSystem_Prm_AirSuspension(varargin) 
% PNEUMATICSSYSTEM_PRM_AIRSUSPENSION returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_PneumaticsSystem_Prm_AirSuspension', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'LoadCompensationMasses', 2, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('kg'), sprintf('Provide min and max compensated masses per bogie')}; ...
{'LoadCompensationPressures', 2, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('Pa'), sprintf('Provide min and max compensated pressures')}; ...
{'MaxPressure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('Pa'), ''}; ...
{'Volume', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('m^3'), ''}; ...
{'SwitchONPressure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('Pa'), ''}; ...
{'SwitchOFFPressure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('Pa'), ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
