function cellInfo = TCMSSystem_Wires(varargin) 
% TCMSSYSTEM_WIRES returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_TCMSSystem_Wires', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'TractionBrakingUnitSum', 1, 'Bus: BD_TCMSSystem_Wires_TBUnitSum', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TractionBrakingTrainWire', 1, 'Bus: BD_TCMSSystem_Wires_TBTrainWire', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorsTrainWire', 1, 'Bus: BD_TCMSSystem_Wires_DoorsTrainWire', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ElectricalTrainWire', 1, 'Bus: BD_TCMSSystem_Wires_ElectricalTrainWire', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TractionBrakingUnitWire', 1, 'Bus: BD_TCMSSystem_Wires_TBUnitWire', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PneumaticTrainSum', 1, 'Bus: BD_TCMSSystem_Wires_PneumaticTrainSum', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ElectricalTrainSum', 1, 'Bus: BD_TCMSSystem_Wires_ElectricalTrainSum', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
