function cellInfo = CBTC_Out_Vehicle_Platform(varargin) 
% CBTC_OUT_VEHICLE_PLATFORM returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_CBTC_Out_Vehicle_Platform', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'LeftSideDoorOpenRequest', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RightSideDoorOpenRequest', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LeftSideDoorCloseRequest', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RightSideDoorCloseRequest', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Door1Inhibited', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Door2Inhibited', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Door3Inhibited', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Door4Inhibited', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LeftSideDoorEnable', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RightSideDoorEnable', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
