function cellInfo = ElectricalSystem_Wires_TrainWires(varargin) 
% ELECTRICALSYSTEM_WIRES_TRAINWIRES returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_ElectricalSystem_Wires_TrainWires', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'TW_TLPC1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW22502', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_UncoupleSignal', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_TLGC1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW25102', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW25103', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW26201', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TDI_110VDC', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW31203', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW51204', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW51206', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_ZeroSpeed', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW81201', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW81203', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TWPantoDNCmd', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW99102', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW99103', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW99104', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW99105', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_LHPBR', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_PADR', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_CC_TrainWakeup', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW41701', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW41704', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW41A04', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_ATOState', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TWNotBraking', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TWMotoring', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TWNotFSB', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TWCabASelected', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TWCabAKeySwitchON', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TWCabBSelected', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TWCabBKeySwitchON', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW31101', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW31101V', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Battery Voltage')}; ...
{'TW31102', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW31103', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW22212', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW11105', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_TSDR', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_TLGC3', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_TLGC2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_TLGC9', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_TLGC10', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_TLGC11', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_SaloonFire', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_Integrity', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW22204', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_VCBTripByCI', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_APSFault', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_VCBTripByAPS', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_LDISRR', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_LDISLR', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TW_11104', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
