function cellInfo = PneumaticsSystem_Prm(varargin) 
% PNEUMATICSSYSTEM_PRM returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_PneumaticsSystem_Prm', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'BrakeControl', 1, 'Bus: BD_PneumaticsSystem_Prm_BrakeControl', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MainReservoir', 1, 'Bus: BD_PneumaticsSystem_Prm_MainReservoir', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MainReservoirPipe', 1, 'Bus: BD_PneumaticsSystem_Prm_MainReservoirPipe', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Sanding', 1, 'Bus: BD_PneumaticsSystem_Prm_Sanding', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AirSuspension', 1, 'Bus: BD_PneumaticsSystem_Prm_AirSuspension', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Horn', 1, 'Bus: BD_PneumaticsSystem_Prm_Horn', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AuxiliaryReservoir', 1, 'Bus: BD_PneumaticsSystem_Prm_AuxiliaryReservoir', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pantograph', 1, 'Bus: BD_PneumaticsSystem_Prm_Pantograph', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BrakeReservoir', 1, 'Bus: BD_PneumaticsSystem_Prm_BrakeReservoir', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BrakeCylinder', 1, 'Bus: BD_PneumaticsSystem_Prm_BrakeCylinder', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ParkBrakes', 1, 'Bus: BD_PneumaticsSystem_Prm_ParkBrakes', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'VCB', 1, 'Bus: BD_PneumaticsSystem_Prm_VCB', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
