function [bus_names, bus_prefix, bus_dir] = prj_bus_names()

bus_names = { ...
	'TCMSSystem_Cfg_Vehicle',...
    'TCMSSystem_In_Vehicle',...
    'TCMSSystem_In_Vehicle_CouplingSystem',...
    'TCMSSystem_In_Vehicle_DisplayControl',...
    'TCMSSystem_In_Vehicle_DisplayControl_Bogie',...
    'TCMSSystem_In_Vehicle_DoorSystem',...
    'TCMSSystem_In_Vehicle_DoorSystem_Door',...
    'TCMSSystem_In_Vehicle_DoorSystem_EmergencyDoor',...
    'TCMSSystem_In_Vehicle_BrakingSystem',...
    'TCMSSystem_In_Vehicle_DynamicsSystem',...
    'TCMSSystem_In_Vehicle_ElectricalSignals',...
    'TCMSSystem_In_Vehicle_Environment',...
    'TCMSSystem_In_Vehicle_Faults',...
    'TCMSSystem_In_Vehicle_InputControlStates',...
	'TCMSSystem_In_Vehicle_Overrides',...
    'TCMSSystem_In_Vehicle_PantographSystem',...
    'TCMSSystem_In_Vehicle_PneumaticsSystem',...
    'TCMSSystem_In_Vehicle_PneumaticsSystem_Bogie',...
	'TCMSSystem_In_Vehicle_TractionSystem',...
    'TCMSSystem_In_Vehicle_TractionSystem_Bogie',...
    'TCMSSystem_In_Vehicle_CBTC',...
    'TCMSSystem_Out_Vehicle',...
    'TCMSSystem_Out_Vehicle_Control',...
    'TCMSSystem_Out_Vehicle_Control_DoorSystem',...
    'TCMSSystem_Out_Vehicle_Control_PantographSystem',...
    'TCMSSystem_Out_Vehicle_Control_PneumaticSystem',...
    'TCMSSystem_Out_Vehicle_Control_TractionBraking',...
    'TCMSSystem_Out_Vehicle_Control_TractionBraking_Bogie',...
    'TCMSSystem_Out_Vehicle_Control_ElectricalSystem',...
    'TCMSSystem_Out_Vehicle_Display',...
    'TCMSSystem_Out_Vehicle_Display_DoorSystem',...
    'TCMSSystem_Out_Vehicle_Display_DoorSystem_Door',...
    'TCMSSystem_Out_Vehicle_Display_ElectricalSystem',...
    'TCMSSystem_Out_Vehicle_Display_Message',...
    'TCMSSystem_Out_Vehicle_Display_MessageList',...
    'TCMSSystem_Out_Vehicle_Display_PantographSystem',...
    'TCMSSystem_Out_Vehicle_Display_PneumaticsSystem',...
    'TCMSSystem_Out_Vehicle_Display_PneumaticsSystem_Bogie',...
    'TCMSSystem_Out_Vehicle_Display_TCMSSystem',...
    'TCMSSystem_Out_Vehicle_Display_TractionBraking',...
    'TCMSSystem_Out_Vehicle_Display_TractionBraking_Bogie',...
    'TCMSSystem_Prm',...
    'TCMSSystem_Wires',...
    'TCMSSystem_Wires_DoorsTrainWire',...
    'TCMSSystem_Wires_ElectricalTrainWire',...
    'TCMSSystem_Wires_ElectricalTrainSum',...
    'TCMSSystem_Wires_PneumaticTrainSum',...
    'TCMSSystem_Wires_TBTrainWire',...
    'TCMSSystem_Wires_TBUnitSum',...
    'TCMSSystem_Wires_TBUnitWire',...
};
    
bus_prefix = 'BD_';

%find the bus_dir based on the relative
%path to this file (prj_bus_names.m)
m_dir = fileparts(mfilename('fullpath'));
bus_dir = fullfile(m_dir, '../data/bus');

end