function cellInfo = PneumaticsSystem_Out_Vehicle_Coupling(varargin) 
% PNEUMATICSSYSTEM_OUT_VEHICLE_COUPLING returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_PneumaticsSystem_Out_Vehicle_Coupling', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'PneumaticCouplerState', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('0 = Off\n1 = Low Volume\n2 = High Volume')}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
