PROMPT Creating DR_SESSIONHEADER view
CREATE OR REPLACE VIEW DR_SESSIONHEADER ( SESSIONID,
HUBID, HUBNAME, DRIVERNAME, DRIVERNO,
INSTRUCTORNAME, SESSIONDATE, SESSIONSIMDATE, SCENARIOID, SCENARIODESCRIPTION,
TRACKID, TRACKNAME, STARTPOSITION, ENDPOSITION,
STARTSTATION, ENDSTATION, STARTOFFSET, ENDOFFSET,
TRAINID, TRAINDESCRIPTION, DURATION, SESSIONENDDATE) AS
SELECT        SSHU.SISE_SIMSESSION_ID,
              PHHU.PHHU_HUB_ID,
              PHHU.PHHU_HUB_NAME,
              SUS1.SUS_FIRSTNAME || ' ' || SUS1.SUS_LASTNAME,
              SITR.SITR_DRIVERNO,
              SUS2.SUS_FIRSTNAME || ' ' || SUS2.SUS_LASTNAME,
              SSHU.SISE_STARTDATE,
              SSHU.SISE_SIM_STARTDATETIME,
              SCEN.SCEN_SCENARIO_ID,
              SCEN.SCEN_DESCRIPTION,
              TRNE.TRNE_TRACKNETWORK_ID,
              TRNE.TRNE_TRACKNETWORK_NAME,
              SSHU.SISE_STARTPOSITION, 
              SSHU.SISE_ENDPOSITION, 
              SEGM1.SEGM_SEGMENT_NAME,
              SEGM2.SEGM_SEGMENT_NAME,
              SSHU.SISE_START_OFFSET,
              SSHU.SISE_END_OFFSET,
              TRA.TRA_TRAIN_ID,
              TRA.TRA_DESCRIPTION,
              SSHU.SISE_DURATION,
              SSHU.SISE_ENDDATE             
FROM        SIMSESSIONHUB SSHU,
            SCENARIO SCEN,
            SCENARIOTRAIN SCTR,
            SIMTRAINEE SITR,
            SIMINSTRUCTOR SII,
            SIMUSER SUS1,
            SIMUSER SUS2,
            TRACKNETWORK TRNE,
            TRAIN TRA,
            SEGMENT SEGM1,
            SEGMENT SEGM2,
            PHYSICALHUB PHHU
WHERE      SCEN.SCEN_SCENARIO_ID = SSHU.SCEN_SCENARIO_ID
       AND SSHU.PHHU_HUB_ID = PHHU.PHHU_HUB_ID
       AND SSHU.SCEN_SCENARIO_ID = SCTR.SCEN_SCENARIO_ID
       AND SSHU.SCTR_SCENARIOTRAIN_ID = SCTR.SCTR_SCENARIOTRAIN_ID
       AND TRNE.TRNE_TRACKNETWORK_ID = SCEN.TRNE_TRACKNETWORK_ID
       AND TRNE.TRNE_TRACKNETWORK_ID = SEGM1.TRNE_TRACKNETWORK_ID
       AND TRNE.TRNE_TRACKNETWORK_ID = SEGM2.TRNE_TRACKNETWORK_ID
       AND SSHU.SEGM_START_SEGMENT_ID = SEGM1.SEGM_SEGMENT_ID
       AND SSHU.SEGM_END_SEGMENT_ID = SEGM2.SEGM_SEGMENT_ID
       AND TRA.TRA_TRAIN_ID = SCTR.TRA_TRAIN_ID 
       AND SITR.SUS_SIMUSER_ID = SSHU.SUS_DRIVER_ID 
       AND SITR.SUS_SIMUSER_ID = SUS1.SUS_SIMUSER_ID 
       AND SII.SUS_SIMUSER_ID = SSHU.SUS_INSTRUCTOR_ID 
       AND SII.SUS_SIMUSER_ID = SUS2.SUS_SIMUSER_ID 
       AND SSHU.SISE_REPLAY = 1 
WITH READ ONLY
/