function [bus_names, bus_prefix, bus_dir] = prj_bus_names()

bus_names = { ...
    'ElectricalSystem_Cfg_Vehicle',...
    'ElectricalSystem_In_Faults',...
    'ElectricalSystem_In_Overrides',...
    'ElectricalSystem_In_Vehicle',...
    'ElectricalSystem_In_Vehicle_Coupling',...
    'ElectricalSystem_In_Vehicle_Doors',...
	'ElectricalSystem_In_Vehicle_Dynamics',...
    'ElectricalSystem_In_Vehicle_InputControlStates',...
    'ElectricalSystem_In_Vehicle_Pantograph',...
    'ElectricalSystem_In_Vehicle_Pneumatics',...
	'ElectricalSystem_In_Vehicle_SignalSys',...
	'ElectricalSystem_In_Vehicle_TCMS',...
    'ElectricalSystem_Out_Vehicle',...
    'ElectricalSystem_Out_Vehicle_Audio',...  
    'ElectricalSystem_Out_Vehicle_Scoring',...  
    'ElectricalSystem_Out_Vehicle_Braking',...  
    'ElectricalSystem_Out_Vehicle_Coupling',...
    'ElectricalSystem_Out_Vehicle_Doors',...
    'ElectricalSystem_Out_Vehicle_MiscOutputs',...
    'ElectricalSystem_Out_Vehicle_MiscOutputs_PAPIS',...
    'ElectricalSystem_Out_Vehicle_OutputControlStates',...
    'ElectricalSystem_Out_Vehicle_Pantograph',...
    'ElectricalSystem_Out_Vehicle_Pneumatics',...
    'ElectricalSystem_Out_Vehicle_TCMS',...
    'ElectricalSystem_In_Vehicle_Traction',...
    'ElectricalSystem_Out_Vehicle_Traction',...
    'ElectricalSystem_Out_Vehicle_SignalSys',...
    'ElectricalSystem_Prm',...
    'ElectricalSystem_Wires',...
    'ElectricalSystem_Wires_CoupledCabsWires',...
    'ElectricalSystem_Wires_MiscWires',...
    'ElectricalSystem_Wires_MiscConnections',...
    'ElectricalSystem_Wires_OrientationWires',...
    'ElectricalSystem_Wires_TrainWires',...
    'ElectricalSystem_Wires_UnitWires',...
};
    
bus_prefix = 'BD_';

%find the bus_dir based on the relative
%path to this file (prj_bus_names.m)
m_dir = fileparts(mfilename('fullpath'));
bus_dir = fullfile(m_dir, '../data/bus');

end