function cellInfo = CouplingSystem_In_Vehicle_Coupler_Dynamics(varargin) 
% COUPLINGSYSTEM_IN_VEHICLE_COUPLER_DYNAMICS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_CouplingSystem_In_Vehicle_Coupler_Dynamics', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'Force', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('N'), sprintf('Total force at the coupler where positive force is acting into the vehicle.')}; ...
{'SpringForce', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('N'), sprintf('Total force due to coupler extension (relatve position of each vehicle)')}; ...
{'DampingForce', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('N'), sprintf('Total force due to coupler damping (relative speed of each vehicle')}; ...
{'BuffForce', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('N'), ''}; ...
{'DraftForce', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('N'), ''}; ...
{'ImpactForce', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('N'), sprintf('This force is an internal instantaneous impulse that does not contribute to the movement calculation as it is dissipated inside the material (if not breakage) at the next step.')}; ...
{'Breakage', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Extension', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'ExtensionRate', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
{'ExternalCoupling', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Mimic', 1, 'Bus: BD_CouplerMimic_InterfaceData', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
