function [bus_names, bus_prefix, bus_dir] = prj_bus_names()

bus_names = { ...
    'CBTC_In_Faults', ...
    'CBTC_Out_Vehicle', ...
    'CBTC_Out_Vehicle_Onboard', ...
    'CBTC_Out_Vehicle_Platform', ...
    'CBTC_Out_Vehicle_Electrical', ...
    'CBTC_Out_Vehicle_TCMS', ...
    'CBTC_Out_Vehicle_DMI', ...
    'SimIntegration_Cfg_Vehicle', ...
    'SimIntegration_Cfg_Vehicle_Equipment', ...
    'SimIntegration_Cfg_Vehicle_Location', ...
    'SimIntegration_Faults_IOControls',...
    'SimIntegration_Faults_Train', ...
    'SimIntegration_Faults_Vehicle', ...
    'SimIntegration_Faults_Vehicle_Processed',...
    'SimIntegration_In_Train', ...
    'SimIntegration_In_Train_CBTC_Tuning', ...
    'SimIntegration_In_Train_Overrides', ...
    'SimIntegration_In_Vehicle', ...
    'SimIntegration_In_Vehicle_CBTC', ...
    'SimIntegration_In_Vehicle_CBTC_Onboard', ...
    'SimIntegration_In_Vehicle_CBTC_Platform', ...
    'SimIntegration_In_Vehicle_Dynamics', ...
    'SimIntegration_In_Vehicle_Environment', ...
    'SimIntegration_In_Vehicle_Overrides',...
    'SimIntegration_Out_Train', ...
    'SimIntegration_Out_Train_Scoring', ...
    'SimIntegration_Out_Vehicle', ...
    'SimIntegration_Out_Vehicle_Audio', ...
    'SimIntegration_Out_Vehicle_Coupling', ...
    'SimIntegration_Out_Vehicle_Scoring', ...
    'SimIntegration_Out_Vehicle_Cfg_Unit',...
    'SimIntegration_Prm',...
	'SimIntegration_In_Vehicle_MotionBaseController', ...
    'SimIntegration_In_Vehicle_MotionBaseController_Effects', ...
    'SimIntegration_In_Vehicle_MotionBaseController_Tuning', ...
	'MotionBase_In_Vehicle', ...
    'MotionBase_In_Vehicle_Dynamics', ...
    'MotionBase_In_Vehicle_Dynamics_Transform', ...
    'MotionBase_In_Vehicle_Environment', ...
    'MotionBase_In_Vehicle_Effects', ...
	'SimIntegration_Out_Vehicle_MotionBaseController', ...
};

bus_prefix = 'BD_';

%find the bus_dir based on the relative
%path to this file (prj_bus_names.m)
m_dir = fileparts(mfilename('fullpath'));
bus_dir = fullfile(m_dir, '../data/bus');

end