function cellInfo = TCMSSystem_Out_Vehicle_Display_PneumaticsSystem(varargin) 
% TCMSSYSTEM_OUT_VEHICLE_DISPLAY_PNEUMATICSSYSTEM returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_TCMSSystem_Out_Vehicle_Display_PneumaticsSystem', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'AllServiceBrakesReleased', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ServiceBrakesApplied', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AllParkBrakesReleased', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ParkBrakeApplied', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MainPipePressure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BrakeCylinderPressure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bogie1BrakeCylinderPressure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bogie2BrakeCylinderPressure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AirSuspensionPressure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MainReservoirPressureGauge', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('Pa'), sprintf('Main Reaservoir Gauge needle pressure in Pa (gauge pressure) \n This is a single location.')}; ...
{'ParkBrakeIsolated', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ParkBrakeApplyFailure', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ParkBrakeReleaseFailure', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bogie', 2, 'Bus: BD_TCMSSystem_Out_Vehicle_Display_PneumaticsSystem_Bogie', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bogie1ServiceBrakeStatus', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bogie2ServiceBrakeStatus', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bogie1ServiceBrakeIsolated', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bogie2ServiceBrakeIsolated', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bogie1ParkingBrakeStatus', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bogie2ParkingBrakeStatus', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bogie1ParkingBrakeIsolated', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bogie2ParkingBrakeIsolated', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bogie1IsolationStatus', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bogie2IsolationStatus', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bogie1SUSPStatus', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bogie2SUSPStatus', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bogie1SUSPFault', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bogie2SUSPFault', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BrakeDemandSignalFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU1EmergencyBrakeFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU2EmergencyBrakeFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU1ServiceBrakeFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU1BrakeNotApplied', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU1BrakeNotReleased', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU1CarLoadPressureLow', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU2CarLoadPressureLow', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECULowRPressure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bogie1ServiceBrakeFault', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU1LoadPressureLow', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AirSuspensionBogie1Deflated', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PantographPipePressureLow', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MainReservoirPressureLow', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
