function cellInfo = TCMSSystem_In_Vehicle_PneumaticsSystem_Bogie(varargin) 
% TCMSSYSTEM_IN_VEHICLE_PNEUMATICSSYSTEM_BOGIE returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_TCMSSystem_In_Vehicle_PneumaticsSystem_Bogie', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'BrakeCylinderPressureGauge', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('Pa'), sprintf('Brake Cylinder Gauge needle pressure in Pa (gauge pressure) \n This is a single location.')}; ...
{'ParkBrakePressureGauge', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('Pa'), sprintf('Park Brake Gauge needle pressure in Pa (gauge pressure) \n This is a single location.')}; ...
{'AirSuspensionLoadPressure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('Pa'), sprintf('Air suspension at the BCU pressure in Pa (gauge pressure)')}; ...
{'EstimatedBogieSupportedMass', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('kg'), sprintf('Mass computed via interpolation of Air Suspension Load Pressure')}; ...
{'ServiceBrakeSwitchStatus', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('Pa'), sprintf('Air suspension at the BCU pressure in Pa (gauge pressure)')}; ...
{'PrakingBrakeSwitchStatus', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('Pa'), sprintf('Air suspension at the BCU pressure in Pa (gauge pressure)')}; ...
{'AirSuspensionSwitchStatus', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('Pa'), sprintf('Air suspension at the BCU pressure in Pa (gauge pressure)')}; ...
{'AirSuspensionPressure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('Pa'), sprintf('Air suspension at the BCU pressure in Pa (gauge pressure)')}; ...
{'BECU1EmergencyBrakeFailure', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU2EmergencyBrakeFailure', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU1ServiceBrakeFailure', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU1BrakeNotApplied', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU1BrakeNotReleased', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU1CarLoadPressureLow', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU2CarLoadPressureLow', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECULowRPressure', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AirSuspensionBogie1Deflated', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU1LoadPressureLow', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
