function cellInfo = TCMSSystem_Out_Vehicle_Display_PantographSystem(varargin) 
% TCMSSYSTEM_OUT_VEHICLE_DISPLAY_PANTOGRAPHSYSTEM returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_TCMSSystem_Out_Vehicle_Display_PantographSystem', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'UnitAtLeastOnePantoUp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Cab Signal - At least one pantograph is up')}; ...
{'UnitAllPantoDown', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Cab Signal - All pantographs are down')}; ...
{'UnitPantoPowerDetected', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Cab Signal - Pantograph Power Detected')}; ...
{'VehiclePantoUp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Vehicle Signal - Pantograph in up position on vehicle')}; ...
{'VehiclePantoDown', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Vehicle Signal - Pantograph in down position on vehicle')}; ...
{'PantographIsolated', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Vehicle Signal - Pantograph Isolated on vehicle')}; ...
{'VehiclePantoRising', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Vehicle Signal - Pantograph rising on vehicle')}; ...
{'VehiclePantoLowering', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Vehicle Signal - Pantograph lowering on vehicle')}; ...
{'PantographPosition', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Vehicle Signal - Pantograph Position')}; ...
{'PantographFault', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Vehicle Signal - Pantograph Fault')}; ...
{'PantoADDFaultMessage', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Vehicle Signal - Pantograph ADD Fault mesg')}; ...
{'PantoORDFaultMessage', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Vehicle Signal - Pantograph ORD Fault mesg')}; ...
{'PantoRaiseFailureMessage', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Vehicle Signal - Pantograph Raise Failure mesg')}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
