function cellInfo = TCMSSystem_Wires_TBUnitSum(varargin) 
% TCMSSYSTEM_WIRES_TBUNITSUM returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_TCMSSystem_Wires_TBUnitSum', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'TractionBogiesEquipped', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BrakingBogiesEquipped', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TractiveEffortAchieved', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EDBrakingEffortAchieved', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TractiveEffortPossible', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EDBrakingEffortPossible', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TractivePowerAchieved', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EDBrakingPowerAchieved', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TractivePowerPossible', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EDBrakingPowerPossible', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EstimatedMass', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TractionBogiesAvailable', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EDBrakingBogiesAvailable', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
