function cellInfo = SimIntegration_In_Vehicle_MotionBaseController_Effects(varargin) 
% SIMINTEGRATION_IN_VEHICLE_MOTIONBASECONTROLLER_EFFECTS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_SimIntegration_In_Vehicle_MotionBaseController_Effects', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'DegradedTrack', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'OnRoughTrack', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
