function cellInfo = ElectricalSystem_Wires(varargin) 
% ELECTRICALSYSTEM_WIRES returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_ElectricalSystem_Wires', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'TrainWires', 1, 'Bus: BD_ElectricalSystem_Wires_TrainWires', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UnitWires', 1, 'Bus: BD_ElectricalSystem_Wires_UnitWires', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'OrientationWires', 1, 'Bus: BD_ElectricalSystem_Wires_OrientationWires', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CoupledCabsWires', 1, 'Bus: BD_ElectricalSystem_Wires_CoupledCabsWires', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MiscWires', 1, 'Bus: BD_ElectricalSystem_Wires_MiscWires', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
