function [bus_names, bus_prefix, bus_dir] = prj_bus_names()

bus_names = { ...
    'IOControls_In_InputControl'...
    'IOControls_In_MCBControl'...
    'IOControls_In_Vehicle'...
    'IOControls_Out_Vehicle'...
    'IOControls_Out_Vehicle_InputStates'...
    'IOControls_Out_Vehicle_MCBTripStates'...
    'IOControls_Out_Vehicle_OutputStates'...
};
    
bus_prefix = 'BD_';

%find the bus_dir based on the relative
%path to this file (prj_bus_names.m)
m_dir = fileparts(mfilename('fullpath'));
bus_dir = fullfile(m_dir, '../data/bus');

end