function cellInfo = TractionSystem_Prm(varargin) 
% TRACTIONSYSTEM_PRM returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_TractionSystem_Prm', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'DesignMaxTractionTorque', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('N*m'), ''}; ...
{'DesignMaxTractionPower', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('W'), ''}; ...
{'DesignTimeToMaxTraction', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('s'), ''}; ...
{'DesignMaxBrakingTorque', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('N*m'), ''}; ...
{'DesignMaxBrakingPower', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('W'), ''}; ...
{'BrakeFadeRampDownSpeeds', 2, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
{'DesignGearingRatio', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DesignGearingEfficiency', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DesignWheelDiameter', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'DesignBogieMotorCount', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AxleHasMotor', 2, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EmergencyBrakeDeactivatesDynamicBrake', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('1 Emergency Brake disables dynamic brake\n0 Emergency Brake does not disable dynamic brake')}; ...
{'WheelSlipProtectionEnable', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('1 Enables Wheel Slip Protection\n0 Disables Wheel Slip Protection')}; ...
{'WheelSlideProtectionEnable', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('1 Enables Wheel Slide Protection\n0 Disables Wheel Slide Protection')}; ...
{'JerkLimit', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MaxContinuousSlipBeforeTractionCutout', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('s'), ''}; ...
{'MaxContinuousSlideBeforeBrakeCutout', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('s'), ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
