function cellInfo = PneumaticsSystem_In_Vehicle_InputControlStates(varargin) 
% PNEUMATICSSYSTEM_IN_VEHICLE_INPUTCONTROLSTATES returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_PneumaticsSystem_In_Vehicle_InputControlStates', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'HornLowIsolationCock', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HornHighIsolationCock', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BrakeSupplyReservoirIsolationCock', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BrakeSupplyReservoirDrainCock', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'InterCarIsolationCockEnd1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'InterCarIsolationCockEnd2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MainReservoirIsolationCock', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MainReservoirDrainCock', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MainAirSupplyIsolationCock', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AirSuspensionSystemIsolationCockBogie1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AirSuspensionSystemIsolationCockBogie2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AirSuspensionSystemDrainCockBogie1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AirSuspensionSystemDrainCockBogie2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AuxiliaryCompressorIsolationCock', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AuxiliaryReservoirIsolationCock', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AuxiliaryReservoirDrainCock', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PantographAirSupplyIsolationCock', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BrakeCylinderIsolationCockBogie1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BrakeCylinderIsolationCockBogie2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ParkingBrakeIsolationCockBogie1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ParkingBrakeIsolationCockBogie2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ParkingBrakeManualReleaseBogie1Handle1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ParkingBrakeManualReleaseBogie1Handle2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ParkingBrakeManualReleaseBogie2Handle1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ParkingBrakeManualReleaseBogie2Handle2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SandingSystemIsolationCockBogie1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SandingSystemIsolationCockBogie2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UncouplingIsolationCock', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AirSuspensionReservoirIsolationCock', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EPIsolationCock', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'VCBIsolationCock', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ORDPlunger', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
