function [bus_names, bus_prefix, bus_dir] = prj_bus_names()

bus_names = { ...
	'PantographSystem_Cfg_Vehicle',...
    'PantographSystem_In_Vehicle',...
    'PantographSystem_In_Vehicle_Control',...
    'PantographSystem_In_Vehicle_Electrical',...
    'PantographSystem_In_Vehicle_Environment',...
    'PantographSystem_In_Vehicle_Faults',...
	'PantographSystem_In_Vehicle_Overrides',...
    'PantographSystem_In_Vehicle_Pneumatics',...
    'PantographSystem_Out_Vehicle',...
    'PantographSystem_Out_Vehicle_TCMS',...
    'PantographSystem_Out_Vehicle_TCMS_Messages',...
    'PantographSystem_Prm',...
};
    
bus_prefix = 'BD_';

%find the bus_dir based on the relative
%path to this file (prj_bus_names.m)
m_dir = fileparts(mfilename('fullpath'));
bus_dir = fullfile(m_dir, '../data/bus');

end