function cellInfo = ElectricalSystem_In_Vehicle(varargin) 
% ELECTRICALSYSTEM_IN_VEHICLE returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_ElectricalSystem_In_Vehicle', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'InputControlStates', 1, 'Bus: BD_ElectricalSystem_In_Vehicle_InputControlStates', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Coupling', 1, 'Bus: BD_ElectricalSystem_In_Vehicle_Coupling', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Dynamics', 1, 'Bus: BD_ElectricalSystem_In_Vehicle_Dynamics', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pneumatics', 1, 'Bus: BD_ElectricalSystem_In_Vehicle_Pneumatics', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Doors', 1, 'Bus: BD_ElectricalSystem_In_Vehicle_Doors', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pantograph', 1, 'Bus: BD_ElectricalSystem_In_Vehicle_Pantograph', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ModelStatus', 1, 'Bus: BD_CommonTrain_Out_ModelStatus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SignalSys', 1, 'Bus: BD_ElectricalSystem_In_Vehicle_SignalSys', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMS', 1, 'Bus: BD_ElectricalSystem_In_Vehicle_TCMS', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TractionSys', 1, 'Bus: BD_ElectricalSystem_In_Vehicle_Traction', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
