function cellInfo = TCMSSystem_In_Vehicle_DisplayControl(varargin) 
% TCMSSYSTEM_IN_VEHICLE_DISPLAYCONTROL returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_TCMSSystem_In_Vehicle_DisplayControl', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'TractionPowerLimit', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('W'), sprintf('-1 Disabled\n0 - inf Power Limit in Watts')}; ...
{'EDBrakingPowerLimit', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('W'), sprintf('-1 Disabled\n0 - inf Power Limit in Watts')}; ...
{'EnableTractionPowerLimit', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EnableEDBrakingPowerLimit', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MaxTractionAccelerationTargetOverride', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('m/s/s'), ''}; ...
{'MaxBrakingDecelerationTargetOverride', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], sprintf('m/s/s'), ''}; ...
{'EnableTractionTargetOverride', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EnableBrakingTargetOverride', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BogieControl', 2, 'Bus: BD_TCMSSystem_In_Vehicle_DisplayControl_Bogie', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PantographIsolationCommand', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RightDoorsEmergencyReleaseCommand', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LeftDoorsEmergencyReleaseCommand', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorRight1DisableCommand', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorLeft1DisableCommand', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorRight2DisableCommand', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorLeft2DisableCommand', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorRight3DisableCommand', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorLeft3DisableCommand', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorRight4DisableCommand', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorLeft4DisableCommand', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorA1IsolateVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorA2IsolateVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorA3IsolateVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorA4IsolateVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorB1IsolateVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorB2IsolateVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorB3IsolateVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorB4IsolateVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LVIsolateBCG1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LVIsolateBCG2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LVCommandPOPB', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ParkBrakeApplyVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ParkBrakeReleaseVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ParkBrakeBypassVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bogie1IsolateVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bogie2IsolateVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HornHigh', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HornLow', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HornIsolate', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSPantoLowerReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSPantoResetReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSPantoRiseReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSReqCtrlVCBNS', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSVCBResetReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSVCBOpenReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSVCBCloseReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSIsolateCI', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSIsolatePanto', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSIsolateVCB', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSIsolateAPS1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSIsolateAPS2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ActivateHTE', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ActivateWashing3Kmph', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ActivateWashing4Kmph', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ActivateWashing5Kmph', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSAPSICBOpen', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSAPSICBClose', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSHVAC1Close', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSHVAC1Open', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSHVAC2Open', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSHVAC2Close', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSFDSCBClose', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSFDSCBOpen', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MVMainCompForcing', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MVMTrBlowersForcingHigh', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MVMTrBlowersForcingLow', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MVCompHoursReset', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TEBEFeedback', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSHVAC1ResetReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSHVAC2ResetReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSHVAC1IsolateReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSHVAC2IsolateReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSHVACSmokeResetReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSFireAlarmResetReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSFDUResetReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ShuntModeMaxSpeed', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ShuntModeMinSpeed', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ATPLowModeMaxSpeed', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ATPLowModeActivated', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ShuntModeActivated', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSWFLIsolationReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCMSPABORBypassReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HVAC1FireDetectorDisableVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EDBHeatAlarmDisableVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CABSmokeDetectorDisableVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SHDEndCubicleRearRight1DisableVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SHDEndCubicleRearRight2DisableVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SHDEndCubicleRearLeft1DisableVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SHDEndCubicleRearLeft2DisableVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LHDDriverDeskDisableVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LHDCIDisableVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LHDLTJBDisableVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SaloonR1FireDetectorDisableVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SaloonR2FireDetectorDisableVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AuxiliaryDeskFireDetectorDisableVDUReq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
