function cellInfo = TCMSSystem_Out_Vehicle_Control(varargin) 
% TCMSSYSTEM_OUT_VEHICLE_CONTROL returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_TCMSSystem_Out_Vehicle_Control', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'DoorSystem', 1, 'Bus: BD_TCMSSystem_Out_Vehicle_Control_DoorSystem', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PantographSystem', 1, 'Bus: BD_TCMSSystem_Out_Vehicle_Control_PantographSystem', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TractionSBraking', 1, 'Bus: BD_TCMSSystem_Out_Vehicle_Control_TractionBraking', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ElectricalSystem', 1, 'Bus: BD_TCMSSystem_Out_Vehicle_Control_ElectricalSystem', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PneumaticSystem', 1, 'Bus: BD_TCMSSystem_Out_Vehicle_Control_PneumaticSystem', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
