function cellInfo = TractionSystem_Out_Vehicle_TCMS_Bogie(varargin) 
% TRACTIONSYSTEM_OUT_VEHICLE_TCMS_BOGIE returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_TractionSystem_Out_Vehicle_TCMS_Bogie', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'TCUStatus', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BogieFaulty', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TractionNotIsolated', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EDBrakeNotIsolated', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCUSlideDetected', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TCUSlipDetected', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TractiveEffortAchieved', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EDBrakingEffortAchieved', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TractiveEffortPossible', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EDBrakingEffortPossible', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TractionPower', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EDBrakingPower', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TractivePowerPossible', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EDBrakingPowerPossible', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MotorSpeeds', 2, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'WSPTractionCutout', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SpeedSensorFault', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
