function cellInfo = SimIntegration_Faults_Vehicle(varargin) 
% SIMINTEGRATION_FAULTS_VEHICLE returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_SimIntegration_Faults_Vehicle', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'WFLFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ODDFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ObstacleDetectedRightSide', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DerailmentDetectedRightSide', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ShutdownFailureVCBOpening', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MCBLightGroupSaloonTripped', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CouplingCircuitNotPowered', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CabEnablingCircuitBreakerTripped', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ExteriorLight1CBTripped', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ExteriorLight2CBTripped', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'InteriorLight1CBTripped', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'InteriorLight2CBTripped', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CMCContactorActivationFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CIFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CIIsolated', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'OHLHighVoltageLevel3', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'OHLLowVoltageLevel2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LineConverterOverCurrentLevel2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DCLinkOverVoltageLevel1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DCLinkLowVoltageLevel1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LineConverterIGBTFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DC110VLowVoltage', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CIMicroprocessorAbnormal', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CILocalCommunicationFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'OverTemperatureOfInverterPowerUnit', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'OverTemperatureOfConverterPowerUnit', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AKOpenFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'KOpenFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MainCircuitEarthFaultLevel2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HeavyWheelSlip', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BrakeDemandSignalFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CIGateSignalAbnormal', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CITCMSCommunicationFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'VCBOpenedByCI', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PantographDownForADDIntervention', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PantographDownForORDIntervention', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PantographDownForBUVDRIntervention', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PantographCircuitNotEnergized', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PantographPipeLowPressure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TransformerOilPressureTooLow', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TransformerOilTemperatureTooHigh', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'VCBOpenedByACOvercurrent', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'VCBOpenedByMTrProtection', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'VCBOpenedByAPS', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PantographRaiseFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PantographLoweringFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CMCContactorDeactivationFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MCB110VDCGroupTripped', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MechanicalCouplerRelayFault', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MasterControllerandTrainLineIncongruence', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BatteryFuseBlown', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BICContactorActivationFault', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LowBatteryVoltageAlarm', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MCBLightGroupTripped', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU1MissingOnSegment', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DLSLFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DCSRFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'APSGroup1Failure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'APSGroup1Isolated', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MCBHVACGroupTripped', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HVAC1MajorFault', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HVAC1SupplyFanMPCBTrip', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HVAC1EmergencyInverterTrip', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HVAC1RCCBTrip', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HVAC1FireMode', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HVAC1ExternalSmokeMode', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HVAC1ReducedMode', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BCGGroup1Failure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BCGGroup1IsolationFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BCGGroup1Isolated', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MCBSignalingGroupTripped', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TrainRadioFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PEA2AlarmActive', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PEA2Failure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PEA3Failure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SCU2Failure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MCBDoorGroupTripped', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EmergencyDoorMechanicalUnlocked', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU1FailureAllSpeedSensors', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU1LoadPressureLow', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorMajorFault', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorDCUFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorMotorCircuitFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU1CarLoadPressureLow', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DCSLFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorUnexpectedUnlocking', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorFailedToLock', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU1BrakeNotApplied', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorCloseObstruction', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorOpenObstruction', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorFailedToUnlock', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU2MinorFault', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECUMajorFault', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECUMajorFaultWired', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECUPWRAndBRKCmdAtSameTime', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MCBAPSGroupTripped', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU1BrakeNotReleased', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECULowRPressure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU2AxleLockedWheelSet2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TransformerOilLevelTooLow', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PantographRisingMissing', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PantographLoweringMissing', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PantographRisingInhibited', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'VCBMissingClosing', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'VCBMissingOpening', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'FailureOfTrainborneATCEquipment', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DMIFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TrainDoorsNotOpeningInATOMode', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'APSCircuitBreakerTripped', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CCTVDisplayHanged', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HeadlightFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HornBlowsContinuously', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EBNotReleased', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TrainDoorLockedClosedRelayFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EmergencyBrakePBOP1NotWorking', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AllDoorCloseIndicatorNotWorking', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorClosePBOP1NotWorking', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorCloseAnnouncementPBNotWorking', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LineVoltageIndicatorNotWorking', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SmokeAlarmCABArea', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HeatAlarmEDB', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PEA1AlarmActive', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PEA1CallNotAcknowledged', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PEA1Failure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PCUFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MCBPAGroupOpen', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TrainDoorNotClosingAtPlatform', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DM1A1DoorNotOpeningAtPlatform', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'WipersNotWorking', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CCDetectDetrainmentDoorOpen', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU1AxleLockedWheelSet1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU1ServiceBrakeFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU1EmergencyBrakeFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AirSuspensionBogie1Deflated', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'WSPActiveBogie1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MCBBrakeGroupTripped', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ParkingBrakeApplicationFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ParkingBrakeReleaseFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CommunicationErrorRIO1RIO2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MCBTCMSGroupTripped', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ER1MajorFault', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'FloodLightNotWorking', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HornIsolatedByVDU', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DLSRFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU2CarLoadPressureLow', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BECU2EmergencyBrakeFailure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'OtherCabOccupiedIndicatorFaulty', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EDNORDeactivatedInRunningTrain', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PressureGuageNotWorking', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RIOMastershipError', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TransformerOilLevelLow', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TransformerOilFlowWarning', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TransformerOilPressureWarning', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TransformerOilTemperatureHigh', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UnexpectedDoorOpeningDetectedByCC', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EmergencyBrakeDueToEBPB', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EmergencyBrakeDueDeadman', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorEmergencyHandleActivation', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BogieDerailed', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
