// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Source/Protobuf/track_position.proto

package core;

public final class TrackPosition {
  private TrackPosition() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface track_positionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:core.track_position)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 segment = 1;</code>
     */
    int getSegment();

    /**
     * <code>double offset = 2;</code>
     */
    double getOffset();

    /**
     * <code>bool heading = 3;</code>
     */
    boolean getHeading();
  }
  /**
   * Protobuf type {@code core.track_position}
   */
  public  static final class track_position extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:core.track_position)
      track_positionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use track_position.newBuilder() to construct.
    private track_position(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private track_position() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new track_position();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private track_position(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              segment_ = input.readInt32();
              break;
            }
            case 17: {

              offset_ = input.readDouble();
              break;
            }
            case 24: {

              heading_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return core.TrackPosition.internal_static_core_track_position_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return core.TrackPosition.internal_static_core_track_position_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              core.TrackPosition.track_position.class, core.TrackPosition.track_position.Builder.class);
    }

    public static final int SEGMENT_FIELD_NUMBER = 1;
    private int segment_;
    /**
     * <code>int32 segment = 1;</code>
     */
    public int getSegment() {
      return segment_;
    }

    public static final int OFFSET_FIELD_NUMBER = 2;
    private double offset_;
    /**
     * <code>double offset = 2;</code>
     */
    public double getOffset() {
      return offset_;
    }

    public static final int HEADING_FIELD_NUMBER = 3;
    private boolean heading_;
    /**
     * <code>bool heading = 3;</code>
     */
    public boolean getHeading() {
      return heading_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (segment_ != 0) {
        output.writeInt32(1, segment_);
      }
      if (offset_ != 0D) {
        output.writeDouble(2, offset_);
      }
      if (heading_ != false) {
        output.writeBool(3, heading_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (segment_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, segment_);
      }
      if (offset_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, offset_);
      }
      if (heading_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, heading_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof core.TrackPosition.track_position)) {
        return super.equals(obj);
      }
      core.TrackPosition.track_position other = (core.TrackPosition.track_position) obj;

      if (getSegment()
          != other.getSegment()) return false;
      if (java.lang.Double.doubleToLongBits(getOffset())
          != java.lang.Double.doubleToLongBits(
              other.getOffset())) return false;
      if (getHeading()
          != other.getHeading()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SEGMENT_FIELD_NUMBER;
      hash = (53 * hash) + getSegment();
      hash = (37 * hash) + OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getOffset()));
      hash = (37 * hash) + HEADING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHeading());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static core.TrackPosition.track_position parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.TrackPosition.track_position parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.TrackPosition.track_position parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.TrackPosition.track_position parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.TrackPosition.track_position parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.TrackPosition.track_position parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.TrackPosition.track_position parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static core.TrackPosition.track_position parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static core.TrackPosition.track_position parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static core.TrackPosition.track_position parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static core.TrackPosition.track_position parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static core.TrackPosition.track_position parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(core.TrackPosition.track_position prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code core.track_position}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:core.track_position)
        core.TrackPosition.track_positionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return core.TrackPosition.internal_static_core_track_position_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return core.TrackPosition.internal_static_core_track_position_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                core.TrackPosition.track_position.class, core.TrackPosition.track_position.Builder.class);
      }

      // Construct using core.TrackPosition.track_position.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        segment_ = 0;

        offset_ = 0D;

        heading_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return core.TrackPosition.internal_static_core_track_position_descriptor;
      }

      @java.lang.Override
      public core.TrackPosition.track_position getDefaultInstanceForType() {
        return core.TrackPosition.track_position.getDefaultInstance();
      }

      @java.lang.Override
      public core.TrackPosition.track_position build() {
        core.TrackPosition.track_position result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public core.TrackPosition.track_position buildPartial() {
        core.TrackPosition.track_position result = new core.TrackPosition.track_position(this);
        result.segment_ = segment_;
        result.offset_ = offset_;
        result.heading_ = heading_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof core.TrackPosition.track_position) {
          return mergeFrom((core.TrackPosition.track_position)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(core.TrackPosition.track_position other) {
        if (other == core.TrackPosition.track_position.getDefaultInstance()) return this;
        if (other.getSegment() != 0) {
          setSegment(other.getSegment());
        }
        if (other.getOffset() != 0D) {
          setOffset(other.getOffset());
        }
        if (other.getHeading() != false) {
          setHeading(other.getHeading());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        core.TrackPosition.track_position parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (core.TrackPosition.track_position) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int segment_ ;
      /**
       * <code>int32 segment = 1;</code>
       */
      public int getSegment() {
        return segment_;
      }
      /**
       * <code>int32 segment = 1;</code>
       */
      public Builder setSegment(int value) {
        
        segment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 segment = 1;</code>
       */
      public Builder clearSegment() {
        
        segment_ = 0;
        onChanged();
        return this;
      }

      private double offset_ ;
      /**
       * <code>double offset = 2;</code>
       */
      public double getOffset() {
        return offset_;
      }
      /**
       * <code>double offset = 2;</code>
       */
      public Builder setOffset(double value) {
        
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double offset = 2;</code>
       */
      public Builder clearOffset() {
        
        offset_ = 0D;
        onChanged();
        return this;
      }

      private boolean heading_ ;
      /**
       * <code>bool heading = 3;</code>
       */
      public boolean getHeading() {
        return heading_;
      }
      /**
       * <code>bool heading = 3;</code>
       */
      public Builder setHeading(boolean value) {
        
        heading_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool heading = 3;</code>
       */
      public Builder clearHeading() {
        
        heading_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:core.track_position)
    }

    // @@protoc_insertion_point(class_scope:core.track_position)
    private static final core.TrackPosition.track_position DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new core.TrackPosition.track_position();
    }

    public static core.TrackPosition.track_position getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<track_position>
        PARSER = new com.google.protobuf.AbstractParser<track_position>() {
      @java.lang.Override
      public track_position parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new track_position(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<track_position> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<track_position> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public core.TrackPosition.track_position getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_track_position_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_core_track_position_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$Source/Protobuf/track_position.proto\022\004" +
      "core\"B\n\016track_position\022\017\n\007segment\030\001 \001(\005\022" +
      "\016\n\006offset\030\002 \001(\001\022\017\n\007heading\030\003 \001(\010b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_core_track_position_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_core_track_position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_core_track_position_descriptor,
        new java.lang.String[] { "Segment", "Offset", "Heading", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
