function cellInfo = ElectricalSystem_Out_Vehicle_SignalSys(varargin) 
% ELECTRICALSYSTEM_OUT_VEHICLE_SIGNALSYS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BD_ElectricalSystem_Out_Vehicle_SignalSys', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'ATCPower', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ATOStartPB', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UTOStartPB', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ATCSafetyBrakeResetPB', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'NotSafetyBrake', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CabActive', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UTOMode', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TBCInFSB', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RMFMode', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DoorEnableBypass', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TrainDoorClosedAndLocked', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RMRMode', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'NoATCBypass', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'TrainIntegrity', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DMIPower', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ATOMode', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ATBMode', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ROSMode', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ATPMode', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EmergencyDoorNotOpen', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'WakeUpStatus', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PassengerEmergencyAlarm', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'FireSmokeInd', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'MechanicalCoupling', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ROSPB', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UTBPB', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LeftDoorOpenPB', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RightDoorOpenPB', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LeftDoorClosePB', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RightDoorClosePB', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
